// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[SystemErr-101000]
	_ = x[ParamsError-101001]
	_ = x[ConnectMysqlErr-101002]
	_ = x[RequestOvertimeErr-101003]
	_ = x[SignErr-101004]
	_ = x[NeTRequestErr-101005]
	_ = x[ParseJsonDataErr-101006]
	_ = x[SaveGameInfoError-401000]
	_ = x[GetGameInfoErr-401001]
	_ = x[GetTokenErr-401002]
	_ = x[GetGameDataErr-401003]
	_ = x[AccountLoginErr-401004]
	_ = x[AccountTokenExpressErr-401005]
	_ = x[SaveGameStatisticsErr-401006]
}

const (
	_ErrCode_name_0 = "Success"
	_ErrCode_name_1 = "系统异常参数异常，请检查连接数据库异常请求发起时间超时参数签名异常网络请求失败解析json数据异常"
	_ErrCode_name_2 = "保存游戏信息异常获取游戏信息异常获取Token信息异常获取Nakama数据异常Nakama账户登录异常Nakama Token过期异常保存游戏统计数据异常"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 12, 36, 57, 81, 99, 117, 139}
	_ErrCode_index_2 = [...]uint8{0, 24, 48, 71, 95, 119, 143, 173}
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case 101000 <= i && i <= 101006:
		i -= 101000
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case 401000 <= i && i <= 401006:
		i -= 401000
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
