// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[StartServerErr-101000]
	_ = x[SystemErr-101001]
	_ = x[ParamsError-101002]
	_ = x[ConnectMysqlErr-101003]
	_ = x[DbErr-101004]
	_ = x[DataDeleteErr-101005]
	_ = x[GetTokenErr-101006]
	_ = x[GetLeaderboardListErr-101007]
	_ = x[GetLeaderboardDetailErr-101008]
	_ = x[ParseJsonDataErr-101009]
	_ = x[GetAccountListErr-101010]
	_ = x[DeleteAccountErr-101011]
	_ = x[EditeAccountErr-101012]
	_ = x[GetAccountDetailErr-101013]
	_ = x[GetAccountBanListErr-101014]
	_ = x[DeleteLeaderboardErr-101015]
	_ = x[AccountUnlinkErr-101016]
	_ = x[GetAccountFriendErr-101017]
	_ = x[DeleteAccountFriendErr-101018]
	_ = x[AccountEnableErr-101019]
	_ = x[AccountDisableErr-101020]
	_ = x[GetMatchDataErr-101021]
	_ = x[GetMatchStateErr-101022]
	_ = x[AccountLoginErr-101023]
	_ = x[AccountTokenExpressErr-101024]
	_ = x[GetGameDataErr-101025]
}

const (
	_ErrCode_name_0 = "Success"
	_ErrCode_name_1 = "启动服务异常系统异常参数异常，请检查连接数据库异常数据库异常DB数据删除异常获取Token信息异常获取Nakama排行榜数据列表异常获取Nakama排行榜数据详情异常解析Nakama json数据异常获取Nakama账户列表异常删除Nakama账户列表异常编辑Nakama账户列表异常获取Nakama账户详情异常获取Nakama禁用账户列表异常删除Nakama排行榜数据异常删除Nakama账户好友关联异常获取Nakama账户好友异常删除Nakama账户好友异常启用Nakama账户异常禁用Nakama账户异常获取Nakama比赛数据异常获取Nakama比赛状态数据异常Nakama账户登录异常Nakama Token过期异常获取Nakama数据异常"
)

var (
	_ErrCode_index_1 = [...]uint16{0, 18, 30, 54, 75, 90, 110, 133, 172, 211, 240, 270, 300, 330, 360, 396, 429, 465, 495, 525, 549, 573, 603, 639, 663, 687, 711}
)

func (i ErrCode) String() string {
	switch {
	case i == 200:
		return _ErrCode_name_0
	case 101000 <= i && i <= 101025:
		i -= 101000
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
